# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_marketdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(blank=True, choices=[('OP', 'Open'), ('CL', 'Close')], default='OP', max_length=2, null=True)),
                ('value', models.FloatField(blank=True, help_text='How much money did we pay in this trade (+ if we payed, - if we got the money)', null=True)),
                ('openorclose', models.CharField(blank=True, help_text='Position opening or position closing', max_length=2, null=True)),
                ('instrument', models.CharField(blank=True, max_length=20, null=True)),
                ('underlying', models.CharField(blank=True, max_length=10, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='operation',
            name='currency',
            field=models.CharField(blank=True, choices=[('EUR', 'Eur'), ('USD', 'Usd'), ('GBP', 'Gbp')], default='EUR', max_length=3, null=True),
        ),
    ]
