# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170625_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='trade_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
