# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_trade_trade_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='currency',
            field=models.CharField(blank=True, choices=[('EUR', 'Eur'), ('USD', 'Usd'), ('GBP', 'Gbp')], default='EUR', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='openorclose',
            field=models.CharField(blank=True, choices=[('OP', 'Open'), ('CL', 'Close')], default='OP', help_text='Position opening or position closing', max_length=2, null=True),
        ),
    ]
