# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170625_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='currency',
            field=models.CharField(blank=True, choices=[('EUR', 'Eur'), ('USD', 'Usd'), ('GBP', 'Gbp')], default='EUR', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='instrument',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
