# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170625_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trade',
            options={'ordering': ['trade_date']},
        ),
        migrations.AddField(
            model_name='trade',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Operation'),
        ),
    ]
