# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170625_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='is_active',
            field=models.NullBooleanField(default=True),
        ),
    ]
