# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_operation_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
