# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20170714_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='exposure',
        ),
        migrations.AddField(
            model_name='operation',
            name='exposure_value',
            field=models.FloatField(blank=True, help_text='The amount of money that we can lose.', null=True),
        ),
    ]
