# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20170714_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='invested',
            field=models.FloatField(blank=True, help_text='The sum values for all the position-opening trades.', null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='price',
            field=models.FloatField(blank=True, help_text='Deprecated', null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='realized_profit',
            field=models.FloatField(blank=True, help_text='... the last time we had a 0 position.', null=True),
        ),
    ]
