# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20170714_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='exposure_value',
            field=models.FloatField(blank=True, help_text='The amount of money we can lose.', null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='position',
            field=models.FloatField(blank=True, help_text='Open position ... counting since the last time we had a 0 position.', null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='realized_profit',
            field=models.FloatField(blank=True, help_text='... calculated at the last time we had a 0 position.', null=True),
        ),
    ]
