# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20170714_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='invested',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='price',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='valuation_date',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='value',
        ),
    ]
