# Generated by Django 2.0.1 on 2018-01-14 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20170714_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Operation'),
        ),
    ]
